"""Violation report PDF generation, following the 12-section order in
research/NotebookLM/violation-report-pdf-specification.md, trimmed to the
in-scope inspector-capture vertical slice (CLAUDE.md section 1): no web
crawler detection source, no eMaap offense-sequence lookup, no automated
notice dispatch. Those sections are replaced with an explicit "not available
in this build" note rather than fabricated data (CLAUDE.md's "no fabricated
numbers" rule).

Generation is two-pass by necessity: a PDF cannot embed the SHA-256 hash of
its own final bytes inside itself. `generate_report` returns the PDF bytes;
the caller (typically the reports API handler) hashes those bytes and passes
the digest to lmd.evidence.bsa63.generate_certificate to produce the
"certificate alongside the report" CLAUDE.md describes -- the certificate is
a sibling artifact, not embedded circularly inside the PDF.
"""
from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any

import qrcode
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from lmd.evidence.bsa63 import PDF_FOOTER_DISCLAIMER
from lmd.limitations import get_known_limitations

_NAVY = colors.Color(10 / 255, 30 / 255, 80 / 255)
_RED = colors.Color(200 / 255, 30 / 255, 30 / 255)
_GREEN = colors.Color(30 / 255, 120 / 255, 30 / 255)
_GRAY_FILL = colors.Color(230 / 255, 235 / 255, 245 / 255)

_SITEWIDE_DISCLAIMER = (
    "This report is an automated pre-screening signal generated by a Legal Metrology "
    "compliance scanning system. It is advisory only. Only a Legal Metrology Officer "
    "may determine a violation and issue a notice."
)

_NOT_AVAILABLE = "Not available in this build (see roadmap; not a live feature)."


def _qr_image(text: str, size_mm: float = 30) -> Image:
    qr = qrcode.QRCode(border=1)
    qr.add_data(text)
    qr.make(fit=True)
    pil_img = qr.make_image(fill_color="black", back_color="white").convert("RGB")
    buf = io.BytesIO()
    pil_img.save(buf, format="PNG")
    buf.seek(0)
    return Image(buf, width=size_mm * mm, height=size_mm * mm)


def _status_color(status: str) -> colors.Color:
    if status in ("FAIL",):
        return _RED
    if status in ("PASS",):
        return _GREEN
    return colors.black


def _footer(canvas, doc):  # noqa: ARG001 -- reportlab callback signature
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.Color(100 / 255, 100 / 255, 100 / 255))
    canvas.drawCentredString(A4[0] / 2, 10 * mm, PDF_FOOTER_DISCLAIMER)
    canvas.drawRightString(A4[0] - 15 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def generate_report(
    case: dict[str, Any],
    scan: dict[str, Any],
    evidence_list: list[dict[str, Any]],
    inspector: dict[str, Any] | None = None,
) -> bytes:
    """Build the violation report PDF and return its raw bytes.

    `case`/`scan`/`evidence_list` are the dict shapes returned by
    lmd.store.repository (get_case / get_scan / list_evidence).
    """
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Heading1"], textColor=_NAVY)
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], textColor=_NAVY)
    body = styles["BodyText"]
    small = ParagraphStyle("small", parent=styles["BodyText"], fontSize=8, textColor=colors.gray)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=20 * mm, bottomMargin=20 * mm)
    story: list[Any] = []

    generation_ts = datetime.now(timezone.utc).isoformat()
    case_id = case["case_id"]

    # --- Section 1: Cover Block ---------------------------------------
    story.append(Paragraph("LEGAL METROLOGY COMPLIANCE -- VIOLATION PRE-SCREENING REPORT", h1))
    story.append(Paragraph("FOR ENFORCEMENT &amp; PROSECUTION REVIEW ONLY", small))
    story.append(Spacer(1, 6))
    cover_table = Table(
        [
            ["Case ID", case_id],
            ["Generated", generation_ts],
            ["Scan ID", scan["scan_id"]],
            ["Overall Verdict", scan["overall_verdict"]],
        ],
        colWidths=[40 * mm, 110 * mm],
    )
    cover_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), _GRAY_FILL),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.gray),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    story.append(Table([[cover_table, _qr_image(f"LMD-CASE:{case_id}")]], colWidths=[150 * mm, 35 * mm]))
    story.append(Spacer(1, 12))

    # --- Section 2: Executive Summary ---------------------------------
    story.append(Paragraph("1. Executive Summary", h2))
    story.append(
        Paragraph(
            f"On {scan['scan_date']}, a compliance scan (source: {scan['scan_source']}) was "
            f"performed and evaluated against ruleset {scan['ruleset_version']}. The automated "
            f"pre-screening result was <b>{scan['overall_verdict']}</b>. This report is advisory "
            "pre-screening output for inspector review, not a legal determination.",
            body,
        )
    )
    story.append(Spacer(1, 8))

    # --- Section 3: Legal Basis table ----------------------------------
    story.append(Paragraph("2. Legal Basis", h2))
    legal_rows = [["Rule ID", "Legal Basis", "Status"]]
    for r in scan["rule_results"]:
        if r["status"] in ("FAIL", "REVIEW"):
            legal_rows.append([r["rule_id"], r["legal_basis"], r["status"]])
    if len(legal_rows) == 1:
        legal_rows.append(["--", "No failing or review rules.", "--"])
    legal_table = Table(legal_rows, colWidths=[25 * mm, 105 * mm, 25 * mm], repeatRows=1)
    legal_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), _NAVY),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.gray),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(legal_table)
    story.append(Spacer(1, 8))

    # --- Section 4: Capture Details -------------------------------------
    story.append(Paragraph("3. Capture Details", h2))
    story.append(
        Paragraph(
            f"Detection source: Inspector-captured scan. Scan source: {scan['scan_source']}. "
            f"Image count: {len(scan.get('image_paths', []))}.",
            body,
        )
    )
    story.append(Spacer(1, 8))

    # --- Section 5: Evidence Exhibits -----------------------------------
    story.append(Paragraph("4. Evidence Exhibits", h2))
    if evidence_list:
        exhibit_rows = [["Exhibit #", "Type", "Capture Time", "SHA-256", "BSA S.63 Cert."]]
        for i, ev in enumerate(evidence_list, start=1):
            exhibit_rows.append(
                [
                    str(i),
                    ev["evidence_type"],
                    ev["capture_timestamp"],
                    ev["sha256_hash"][:16] + "...",
                    ev.get("bsa_s63_certificate_id") or "--",
                ]
            )
        exhibit_table = Table(exhibit_rows, colWidths=[18 * mm, 30 * mm, 40 * mm, 40 * mm, 42 * mm], repeatRows=1)
        exhibit_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), _NAVY),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.gray),
                    ("FONTSIZE", (0, 0), (-1, -1), 7),
                ]
            )
        )
        story.append(exhibit_table)
    else:
        story.append(Paragraph("No evidence artifacts recorded for this case.", body))
    story.append(Spacer(1, 8))

    # --- Section 6: Rule-by-rule verdict table --------------------------
    story.append(Paragraph("5. Rule-by-Rule Verdict Table", h2))
    rule_rows = [["Rule ID", "Category", "Severity", "Status", "Message"]]
    for r in scan["rule_results"]:
        rule_rows.append([r["rule_id"], r["category"], r["severity"], r["status"], r["message"][:80]])
    rule_table = Table(rule_rows, colWidths=[20 * mm, 25 * mm, 20 * mm, 20 * mm, 85 * mm], repeatRows=1)
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), _NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.gray),
        ("FONTSIZE", (0, 0), (-1, -1), 7),
    ]
    for row_idx, r in enumerate(scan["rule_results"], start=1):
        style_cmds.append(("TEXTCOLOR", (3, row_idx), (3, row_idx), _status_color(r["status"])))
    rule_table.setStyle(TableStyle(style_cmds))
    story.append(rule_table)
    story.append(PageBreak())

    # --- Section 7: Inspector Verification & Remarks --------------------
    story.append(Paragraph("6. Inspector Verification &amp; Remarks", h2))
    inspector_name = inspector.get("name") if inspector else "(unassigned)"
    inspector_id = inspector.get("inspector_id") if inspector else "(unassigned)"
    story.append(
        Paragraph(
            f"Inspector: {inspector_name} (ID: {inspector_id})<br/>"
            f"Verified at: {case.get('verified_at') or '(not yet verified)'}<br/>"
            "Reason to believe (Section 15(4), Legal Metrology Act 2009):",
            body,
        )
    )
    story.append(Paragraph(case.get("reason_to_believe_note") or "(none recorded)", body))
    story.append(Spacer(1, 8))

    # --- Section 8: Offense Classification -------------------------------
    story.append(Paragraph("7. Offense Classification &amp; Penalty Computation", h2))
    story.append(Paragraph(f"Offense-sequence lookup (eMaap): {_NOT_AVAILABLE}", body))
    story.append(Spacer(1, 8))

    # --- Section 9: Enforcement Action Log -------------------------------
    story.append(Paragraph("8. Enforcement Action Log", h2))
    story.append(Paragraph(f"Automated notice dispatch: {_NOT_AVAILABLE}", body))
    story.append(Spacer(1, 8))

    # --- Section 10: Officer Determination & Signature -------------------
    story.append(Paragraph("9. Officer Determination &amp; Signature Block", h2))
    story.append(
        Paragraph(
            "[ SYSTEM-GENERATED -- NOT A DIGITAL SIGNATURE CERTIFICATE (DSC) ]<br/>"
            "Inspector Signature Zone: ____________________<br/>"
            f"Date: {generation_ts[:10]}",
            body,
        )
    )
    story.append(Spacer(1, 8))

    # --- Section 11: Known Limitations of This Analysis ------------------
    story.append(Paragraph("10. Known Limitations of This Analysis", h2))
    story.append(
        Paragraph(
            "This system is an advisory pre-screening signal, not a legal adjudication. The gaps "
            "below are deliberate and disclosed, not hidden defects; see /api/v1/limitations for the "
            "machine-readable form.",
            body,
        )
    )
    for entry in get_known_limitations()["limitations"]:
        story.append(Paragraph(f"&bull; [{entry['area']}/{entry['status']}] {entry['detail']}", small))
    story.append(Spacer(1, 8))

    # --- Section 12: Annexures --------------------------------------------
    story.append(Paragraph("11. Annexures", h2))
    story.append(Paragraph("Extraction envelope and full system configuration available via the case API.", body))

    story.append(Spacer(1, 12))
    story.append(Paragraph(_SITEWIDE_DISCLAIMER, small))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()
