"""Violation report PDF generation, following the 12-section order in
research/NotebookLM/violation-report-pdf-specification.md, trimmed to the
in-scope inspector-capture vertical slice (CLAUDE.md section 1): no web
crawler detection source, no eMaap offense-sequence lookup, no automated
notice dispatch. Those sections are replaced with an explicit "not available
in this build" note rather than fabricated data (CLAUDE.md's "no fabricated
numbers" rule).

Generation is two-pass by necessity: a PDF cannot embed the SHA-256 hash of
its own final bytes inside itself. `generate_report` returns the PDF bytes;
the caller (typically the reports API handler) hashes those bytes and passes
the digest to lmd.evidence.bsa63.generate_certificate to produce the
"certificate alongside the report" CLAUDE.md describes -- the certificate is
a sibling artifact, not embedded circularly inside the PDF.
"""
from __future__ import annotations

import base64
import io
from datetime import datetime, timezone
from typing import Any

import qrcode
from PIL import Image as PILImage
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from lmd.evidence.bsa63 import PDF_FOOTER_DISCLAIMER
from lmd.evidence.image_codec import compress_for_storage
from lmd.limitations import get_known_limitations

_NAVY = colors.Color(10 / 255, 30 / 255, 80 / 255)
_RED = colors.Color(200 / 255, 30 / 255, 30 / 255)
_GREEN = colors.Color(30 / 255, 120 / 255, 30 / 255)
_GRAY_FILL = colors.Color(230 / 255, 235 / 255, 245 / 255)

_SITEWIDE_DISCLAIMER = (
    "This report is an automated pre-screening signal generated by a Legal Metrology "
    "compliance scanning system. It is advisory only. Only a Legal Metrology Officer "
    "may determine a violation and issue a notice."
)

_NOT_AVAILABLE = "Not available in this build (see roadmap; not a live feature)."


def _esc(value: Any) -> str:
    """Escape a raw data value for embedding inside a reportlab Paragraph,
    which parses a small XML-like markup subset -- unescaped '&'/'<'/'>' in
    case data (e.g. a legal-basis citation containing '&') would otherwise
    raise or silently mis-render."""
    text = "" if value is None else str(value)
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _qr_image(text: str, size_mm: float = 30) -> Image:
    qr = qrcode.QRCode(border=1)
    qr.add_data(text)
    qr.make(fit=True)
    pil_img = qr.make_image(fill_color="black", back_color="white").convert("RGB")
    buf = io.BytesIO()
    pil_img.save(buf, format="PNG")
    buf.seek(0)
    return Image(buf, width=size_mm * mm, height=size_mm * mm)


def _embed_image(image_bytes: bytes | None, max_width_mm: float = 160, max_height_mm: float = 110) -> Image | None:
    """Scale an in-memory image to fit within the given box, preserving
    aspect ratio (reportlab's Image() distorts otherwise). Returns None
    rather than raising if no bytes were supplied or they are unreadable --
    a report must still generate for a case whose image is missing."""
    if not image_bytes:
        return None
    try:
        with PILImage.open(io.BytesIO(image_bytes)) as im:
            w_px, h_px = im.size
    except Exception:
        return None
    if not w_px or not h_px:
        return None
    aspect = h_px / w_px
    width, height = max_width_mm, max_width_mm * aspect
    if height > max_height_mm:
        height = max_height_mm
        width = height / aspect
    return Image(io.BytesIO(image_bytes), width=width * mm, height=height * mm)


def _status_color(status: str) -> colors.Color:
    if status in ("FAIL",):
        return _RED
    if status in ("PASS",):
        return _GREEN
    return colors.black


def _footer(canvas, doc):  # noqa: ARG001 -- reportlab callback signature
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.Color(100 / 255, 100 / 255, 100 / 255))
    canvas.drawCentredString(A4[0] / 2, 10 * mm, PDF_FOOTER_DISCLAIMER)
    canvas.drawRightString(A4[0] - 15 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def generate_report(
    case: dict[str, Any],
    scan: dict[str, Any],
    evidence_list: list[dict[str, Any]],
    inspector: dict[str, Any] | None = None,
) -> bytes:
    """Build the violation report PDF and return its raw bytes.

    `case`/`scan`/`evidence_list` are the dict shapes returned by
    lmd.store.repository (get_case / get_scan / list_evidence).
    """
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Heading1"], textColor=_NAVY)
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], textColor=_NAVY)
    body = styles["BodyText"]
    small = ParagraphStyle("small", parent=styles["BodyText"], fontSize=8, textColor=colors.gray)
    # Table-cell paragraph styles: reportlab's Table does not wrap raw
    # strings -- a value wider than its colWidth simply overflows and is
    # drawn on top of the neighbouring column. Wrapping every variable-length
    # cell in a Paragraph (which *does* wrap to its cell width) is the fix
    # for the Status/Message (and similar) overlap defect. White colour is
    # set per-cell below for header rows since Paragraph text colour isn't
    # controlled by TableStyle TEXTCOLOR commands.
    cell = ParagraphStyle("cell", parent=styles["BodyText"], fontSize=7.5, leading=9.5)
    cell_header = ParagraphStyle("cell_header", parent=cell, textColor=colors.white, fontName="Helvetica-Bold")
    cell_mono = ParagraphStyle("cell_mono", parent=cell, fontName="Courier")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=20 * mm, bottomMargin=20 * mm)
    story: list[Any] = []

    generation_ts = datetime.now(timezone.utc).isoformat()
    case_id = case["case_id"]

    # --- Section 1: Cover Block ---------------------------------------
    story.append(Paragraph("LEGAL METROLOGY COMPLIANCE -- VIOLATION PRE-SCREENING REPORT", h1))
    story.append(Paragraph("FOR ENFORCEMENT &amp; PROSECUTION REVIEW ONLY", small))
    story.append(Spacer(1, 6))
    cover_table = Table(
        [
            ["Case ID", case_id],
            ["Generated", generation_ts],
            ["Scan ID", scan["scan_id"]],
            ["Overall Verdict", scan["overall_verdict"]],
        ],
        colWidths=[40 * mm, 110 * mm],
    )
    cover_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), _GRAY_FILL),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.gray),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    story.append(Table([[cover_table, _qr_image(f"LMD-CASE:{case_id}")]], colWidths=[150 * mm, 35 * mm]))
    story.append(Spacer(1, 12))

    # --- Section 2: Executive Summary ---------------------------------
    story.append(Paragraph("1. Executive Summary", h2))
    story.append(
        Paragraph(
            f"On {scan['scan_date']}, a compliance scan (source: {scan['scan_source']}) was "
            f"performed and evaluated against ruleset {scan['ruleset_version']}. The automated "
            f"pre-screening result was <b>{scan['overall_verdict']}</b>. This report is advisory "
            "pre-screening output for inspector review, not a legal determination.",
            body,
        )
    )
    story.append(Spacer(1, 8))

    # --- Section 3: Legal Basis table ----------------------------------
    story.append(Paragraph("2. Legal Basis", h2))
    legal_rows = [
        [Paragraph("Rule ID", cell_header), Paragraph("Legal Basis", cell_header), Paragraph("Status", cell_header)]
    ]
    for r in scan["rule_results"]:
        if r["status"] in ("FAIL", "REVIEW"):
            status_style = ParagraphStyle("st", parent=cell, textColor=_status_color(r["status"]), fontName="Helvetica-Bold")
            legal_rows.append(
                [
                    Paragraph(_esc(r["rule_id"]), cell_mono),
                    Paragraph(_esc(r["legal_basis"]), cell),
                    Paragraph(_esc(r["status"]), status_style),
                ]
            )
    if len(legal_rows) == 1:
        legal_rows.append([Paragraph("--", cell), Paragraph("No failing or review rules.", cell), Paragraph("--", cell)])
    legal_table = Table(legal_rows, colWidths=[25 * mm, 105 * mm, 25 * mm], repeatRows=1)
    legal_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), _NAVY),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.gray),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]
        )
    )
    story.append(legal_table)
    story.append(Spacer(1, 8))

    # --- Section 4: Capture Details -------------------------------------
    story.append(Paragraph("3. Capture Details", h2))
    images_base64 = scan.get("images_base64") or {}
    story.append(
        Paragraph(
            f"Detection source: Inspector-captured scan. Scan source: {scan['scan_source']}. "
            f"Image count: {sum(1 for v in images_base64.values() if v)}.",
            body,
        )
    )
    story.append(Spacer(1, 6))
    image_slots = [
        ("original", "Captured product photograph (original upload)"),
        ("overlay", "Annotated overlay (OCR confidence colour-coded)"),
    ]
    embedded_any = False
    for key, label in image_slots:
        b64 = images_base64.get(key)
        image_bytes = base64.b64decode(b64) if b64 else None
        if image_bytes is not None:
            # The PDF itself is stored as a single base64 field
            # (repository.save_report), so both embedded images share that
            # one field's 1 MiB Firestore ceiling -- a much tighter budget
            # per image than the scan document gets, which has one field
            # each. Re-compress down before embedding rather than reusing
            # the scan's already-compressed bytes as-is.
            image_bytes = compress_for_storage(image_bytes, max_bytes=200_000, max_dimension_px=900)
        img = _embed_image(image_bytes)
        if img is None:
            continue
        embedded_any = True
        story.append(Paragraph(label, small))
        story.append(img)
        story.append(Spacer(1, 6))
    if not embedded_any:
        story.append(Paragraph("No capture image could be embedded (not stored with this scan).", body))
    story.append(Spacer(1, 8))

    # --- Section 5: Evidence Exhibits -----------------------------------
    story.append(Paragraph("4. Evidence Exhibits", h2))
    if evidence_list:
        exhibit_rows = [
            [Paragraph(h, cell_header) for h in ["Exhibit #", "Type", "Capture Time", "SHA-256", "BSA S.63 Cert."]]
        ]
        for i, ev in enumerate(evidence_list, start=1):
            exhibit_rows.append(
                [
                    Paragraph(str(i), cell),
                    Paragraph(_esc(ev["evidence_type"]), cell),
                    Paragraph(_esc(ev["capture_timestamp"]), cell_mono),
                    Paragraph(_esc(ev["sha256_hash"][:16] + "..."), cell_mono),
                    Paragraph(_esc(ev.get("bsa_s63_certificate_id") or "--"), cell_mono),
                ]
            )
        exhibit_table = Table(exhibit_rows, colWidths=[18 * mm, 30 * mm, 40 * mm, 40 * mm, 42 * mm], repeatRows=1)
        exhibit_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), _NAVY),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.gray),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ]
            )
        )
        story.append(exhibit_table)
    else:
        story.append(Paragraph("No evidence artifacts recorded for this case.", body))
    story.append(Spacer(1, 8))

    # --- Section 6: Rule-by-rule verdict table --------------------------
    story.append(Paragraph("5. Rule-by-Rule Verdict Table", h2))
    rule_rows = [[Paragraph(h, cell_header) for h in ["Rule ID", "Category", "Severity", "Status", "Message"]]]
    for r in scan["rule_results"]:
        status_style = ParagraphStyle(
            f"st_{r['rule_id']}", parent=cell, textColor=_status_color(r["status"]), fontName="Helvetica-Bold"
        )
        # No [:80] truncation: truncating a raw string was a symptom of the
        # same "text doesn't fit its cell" problem this fix addresses --
        # wrapping in a Paragraph lets the row grow taller instead, so the
        # full message is always shown rather than silently cut off.
        rule_rows.append(
            [
                Paragraph(_esc(r["rule_id"]), cell_mono),
                Paragraph(_esc(r["category"]), cell),
                Paragraph(_esc(r["severity"]), cell),
                Paragraph(_esc(r["status"]), status_style),
                Paragraph(_esc(r["message"]), cell),
            ]
        )
    # Widths sum to 170mm (A4 minus 20mm margins each side); Message keeps
    # the largest share since it holds the longest text.
    rule_table = Table(rule_rows, colWidths=[20 * mm, 25 * mm, 20 * mm, 22 * mm, 83 * mm], repeatRows=1)
    rule_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), _NAVY),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.gray),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]
        )
    )
    story.append(rule_table)
    story.append(PageBreak())

    # --- Section 7: Inspector Verification & Remarks --------------------
    story.append(Paragraph("6. Inspector Verification &amp; Remarks", h2))
    inspector_name = inspector.get("name") if inspector else "(unassigned)"
    inspector_id = inspector.get("inspector_id") if inspector else "(unassigned)"
    story.append(
        Paragraph(
            f"Inspector: {inspector_name} (ID: {inspector_id})<br/>"
            f"Verified at: {case.get('verified_at') or '(not yet verified)'}<br/>"
            "Reason to believe (Section 15(4), Legal Metrology Act 2009):",
            body,
        )
    )
    story.append(Paragraph(case.get("reason_to_believe_note") or "(none recorded)", body))
    story.append(Spacer(1, 8))

    # --- Section 8: Offense Classification -------------------------------
    story.append(Paragraph("7. Offense Classification &amp; Penalty Computation", h2))
    story.append(Paragraph(f"Offense-sequence lookup (eMaap): {_NOT_AVAILABLE}", body))
    story.append(Spacer(1, 8))

    # --- Section 9: Enforcement Action Log -------------------------------
    story.append(Paragraph("8. Enforcement Action Log", h2))
    story.append(Paragraph(f"Automated notice dispatch: {_NOT_AVAILABLE}", body))
    story.append(Spacer(1, 8))

    # --- Section 10: Officer Determination & Signature -------------------
    story.append(Paragraph("9. Officer Determination &amp; Signature Block", h2))
    story.append(
        Paragraph(
            "[ SYSTEM-GENERATED -- NOT A DIGITAL SIGNATURE CERTIFICATE (DSC) ]<br/>"
            "Inspector Signature Zone: ____________________<br/>"
            f"Date: {generation_ts[:10]}",
            body,
        )
    )
    story.append(Spacer(1, 8))

    # --- Section 11: Known Limitations of This Analysis ------------------
    story.append(Paragraph("10. Known Limitations of This Analysis", h2))
    story.append(
        Paragraph(
            "This system is an advisory pre-screening signal, not a legal adjudication. The gaps "
            "below are deliberate and disclosed, not hidden defects; see /api/v1/limitations for the "
            "machine-readable form.",
            body,
        )
    )
    for entry in get_known_limitations()["limitations"]:
        story.append(Paragraph(f"&bull; [{entry['area']}/{entry['status']}] {entry['detail']}", small))
    story.append(Spacer(1, 8))

    # --- Section 12: Annexures --------------------------------------------
    story.append(Paragraph("11. Annexures", h2))
    story.append(Paragraph("Extraction envelope and full system configuration available via the case API.", body))

    story.append(Spacer(1, 12))
    story.append(Paragraph(_SITEWIDE_DISCLAIMER, small))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()
